export type UserRole = "staff" | "admin" | "superuser";

export type Permission =
  // Orders
  | "pos.orders.add"
  | "pos.orders.read"
  | "pos.orders.read_own"
  | "pos.orders.change"
  | "pos.orders.change_own"
  | "pos.orders.delete"
  | "pos.orders.manage"
  | "pos.orders.manage_own"
  | "pos.orders.refund"
  // Tables
  | "pos.tables.add"
  | "pos.tables.read"
  | "pos.tables.read_own"
  | "pos.tables.change"
  | "pos.tables.change_own"
  | "pos.tables.delete"
  | "pos.tables.manage"
  | "pos.tables.manage_own"
  | "pos.tables.refund"
  // Drawer (cash drawer)
  | "pos.drawer.add"
  | "pos.drawer.read"
  | "pos.drawer.read_own"
  | "pos.drawer.change"
  | "pos.drawer.change_own"
  | "pos.drawer.delete"
  | "pos.drawer.manage"
  | "pos.drawer.manage_own"
  | "pos.drawer.refund"
  // Settings
  | "pos.settings.add"
  | "pos.settings.read"
  | "pos.settings.read_own"
  | "pos.settings.change"
  | "pos.settings.change_own"
  | "pos.settings.delete"
  | "pos.settings.manage"
  | "pos.settings.manage_own"
  | "pos.settings.refund"
  // Payments
  | "pos.payments.add"
  | "pos.payments.read"
  | "pos.payments.read_own"
  | "pos.payments.change"
  | "pos.payments.change_own"
  | "pos.payments.delete"
  | "pos.payments.manage"
  | "pos.payments.manage_own"
  | "pos.payments.refund"
  // Catalog
  | "pos.catalog.add"
  | "pos.catalog.read"
  | "pos.catalog.read_own"
  | "pos.catalog.change"
  | "pos.catalog.change_own"
  | "pos.catalog.delete"
  | "pos.catalog.manage"
  | "pos.catalog.manage_own"
  | "pos.catalog.refund"
  // Customers
  | "pos.customers.add"
  | "pos.customers.read"
  | "pos.customers.read_own"
  | "pos.customers.change"
  | "pos.customers.change_own"
  | "pos.customers.delete"
  | "pos.customers.manage"
  | "pos.customers.manage_own"
  | "pos.customers.refund"
  // Reports
  | "pos.reports.add"
  | "pos.reports.read"
  | "pos.reports.read_own"
  | "pos.reports.change"
  | "pos.reports.change_own"
  | "pos.reports.delete"
  | "pos.reports.manage"
  | "pos.reports.manage_own"
  | "pos.reports.refund"
  // Staff
  | "pos.staff.add"
  | "pos.staff.read"
  | "pos.staff.read_own"
  | "pos.staff.change"
  | "pos.staff.change_own"
  | "pos.staff.delete"
  | "pos.staff.manage"
  | "pos.staff.manage_own"
  | "pos.staff.refund"
  // Discounts
  | "pos.discounts.add"
  | "pos.discounts.read"
  | "pos.discounts.read_own"
  | "pos.discounts.change"
  | "pos.discounts.change_own"
  | "pos.discounts.delete"
  | "pos.discounts.manage"
  | "pos.discounts.manage_own"
  | "pos.discounts.refund"
  // Receipts
  | "pos.receipts.add"
  | "pos.receipts.read"
  | "pos.receipts.read_own"
  | "pos.receipts.change"
  | "pos.receipts.change_own"
  | "pos.receipts.delete"
  | "pos.receipts.manage"
  | "pos.receipts.manage_own"
  | "pos.receipts.refund"
  // Platform
  | "pos.platform.add"
  | "pos.platform.read"
  | "pos.platform.read_own"
  | "pos.platform.change"
  | "pos.platform.change_own"
  | "pos.platform.delete"
  | "pos.platform.manage"
  | "pos.platform.manage_own"
  | "pos.platform.refund"
  // Config
  | "pos.config.view"
  | "pos.config.manage"
  // Users
  | "pos.users.manage";

export interface UserProfile {
  id: string;
  email: string;
  fullName: string;
  roles: UserRole[];
  permissions: Permission[];
  organizationId: string;
  tenantId: string;
  tenantSlug: string;
  isPlatformOwner?: boolean;
  isSuperUser?: boolean;
}
