'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useHotelRoom, useRoomFolio, useCheckIn, useCheckOut, useLateCheckout, usePostFolioCharge, useBookingPolicy, useUpdateRoomStatus } from '@/hooks/useHotel';
import { Card, CardContent } from '@/components/ui/base';
import { cn, formatCurrency } from '@/lib/utils';
import {
  ArrowLeft,
  BedDouble,
  Clock,
  Loader2,
  LogIn,
  LogOut,
  PackageSearch,
  Pencil,
  Receipt,
  ShieldAlert,
  Wallet,
  X,
} from 'lucide-react';
import Link from 'next/link';
import { toast } from 'sonner';
import { apiErrorMessage } from '@/lib/api/error-message';
import { ModuleGate } from '@/components/auth/module-gate';
import { ModuleUnavailablePage } from '@/components/auth/module-unavailable';
import { FeatureGate } from '@bengo-hub/shared-ui-lib/subscription';
import { FeatureLocked } from '@/components/auth/feature-locked';
import { CheckoutPanel } from '@/components/pos/hotel/checkout-panel';
import { DamageReportModal } from '@/components/pos/hotel/damage-report-modal';
import { EditGuestModal } from '@/components/pos/hotel/edit-guest-modal';
import { LostFoundModal } from '@/components/pos/hotel/lost-found-modal';
import { HotelTenderPicker } from '@/components/pos/hotel/payment-method-picker';

// Folio charge types a front-desk agent can post manually from this form. Mirrors the
// subset of pos-api's RoomFolioItem.charge_type enum that isn't already posted by a
// dedicated flow elsewhere (room_charge = auto at check-in, amenity/facility = their own
// charge buttons, late_checkout = the Late Checkout action, conference/meal_voucher =
// generated by the conference module).
const CHARGE_TYPES = [
  { value: 'food', label: 'Food' },
  { value: 'minibar', label: 'Minibar' },
  { value: 'laundry', label: 'Laundry' },
  { value: 'room_service', label: 'Room Service' },
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'damage', label: 'Damage / Fine' },
  { value: 'other', label: 'Other' },
];

// Statuses CheckIn's backend gate actually accepts (available|reserved) vs. not — mirrors
// hotel.go's CheckIn handler exactly so the UI never offers an action the API will 409 on.
const CHECK_IN_BLOCKED_STATUSES = new Set(['cleaning', 'maintenance', 'occupied', 'checkout']);

const ROOM_STATUS_COPY: Record<string, { title: string; body: string }> = {
  available: { title: 'This room is available', body: 'Check in a guest to open their stay, post room charges, and start the folio.' },
  cleaning: { title: 'This room is being cleaned', body: 'Housekeeping hasn’t marked it ready yet — finish the cleaning task to free it up, or override below.' },
  maintenance: { title: 'This room is under maintenance', body: 'Out of service until the maintenance task is completed, or override below.' },
  reserved: { title: 'This room is reserved', body: 'Held for an upcoming booking — you can still check a guest in directly if they’ve arrived.' },
  checkout: { title: 'This room just checked out', body: 'Awaiting housekeeping before it’s bookable again.' },
};

function RoomDetailPageInner() {
  const params = useParams();
  const orgSlug = params?.orgSlug as string;
  const roomId = params?.roomId as string;
  const router = useRouter();

  const [checkInForm, setCheckInForm] = useState({
    first_name: '', last_name: '', email: '', phone: '',
    nationality: '', id_type: 'national_id', id_number: '', id_document_url: '',
    adults: '1', children: '0', child_ages: '',
    expected_arrival_at: '', expected_departure_at: '', nights: '1',
  });
  const [showCheckIn, setShowCheckIn] = useState(false);
  const [showCheckout, setShowCheckout] = useState(false);
  // Whether the checkout panel, once open, defaults to also checking the guest out when the
  // balance clears — true for "Checkout & Settle Bill", false for "Settle Now" (take a mid-stay
  // payment, e.g. the settle_at_checkout guest who didn't pay upfront, without ending the stay).
  const [checkoutPanelDefaultsToCheckout, setCheckoutPanelDefaultsToCheckout] = useState(true);
  const [showDamageReport, setShowDamageReport] = useState(false);
  const [showLostFound, setShowLostFound] = useState(false);
  const [showEditGuest, setShowEditGuest] = useState(false);
  const [checkInPaymentMethod, setCheckInPaymentMethod] = useState('');
  const [checkInPaymentReference, setCheckInPaymentReference] = useState('');

  function setField(key: keyof typeof checkInForm, value: string) {
    setCheckInForm((f) => ({ ...f, [key]: value }));
  }

  const { data: room, isLoading: roomLoading } = useHotelRoom(roomId);
  const currency = room?.currency ?? 'KES';
  const isOccupied = room?.status === 'occupied';
  // GetRoom now returns the room's most RECENT stay regardless of status, not just an active
  // one — a room fresh out of checkout ("cleaning") has no active guest but front desk/
  // housekeeping still needs to see who was just there (for a damage report or a lost-item
  // claim raised right after checkout). lastGuest is that same row read for display purposes;
  // guest stays the narrower "currently active" view the check-in/checkout actions rely on.
  const lastGuest = room?.edges?.guests?.[0] ?? null;
  const guest = lastGuest?.status === 'active' ? lastGuest : null;
  const { data: folio = [] } = useRoomFolio(roomId, isOccupied);
  const { data: bookingPolicy } = useBookingPolicy();
  const paymentTiming = bookingPolicy?.payment_timing ?? 'settle_at_checkout';
  const requiresUpfrontPayment = paymentTiming === 'pay_upfront';
  const checkInNights = parseInt(checkInForm.nights) || 1;
  const checkoutTimeDefault = bookingPolicy?.checkout_time || '10:00';

  // Occupancy-based pricing estimate — mirrors pos-api's occupancySurchargePerNight exactly
  // (base occupancy adults free, extra adults/children beyond that surcharge per night) so the
  // total shown here before Confirm matches what actually gets charged. base_occupancy_adults<=0
  // means the property hasn't configured this: stays a flat rate-times-nights estimate, unchanged
  // from before this feature existed.
  const baseOccupancyAdults = bookingPolicy?.base_occupancy_adults ?? 0;
  const checkInAdults = Math.max(1, parseInt(checkInForm.adults) || 1);
  const checkInChildAges = checkInForm.child_ages.split(',').map((s) => parseInt(s.trim(), 10)).filter((n) => Number.isFinite(n) && n >= 0);
  const extraAdultCount = baseOccupancyAdults > 0 ? Math.max(0, checkInAdults - baseOccupancyAdults) : 0;
  const extraAdultCharge = extraAdultCount * (bookingPolicy?.extra_adult_rate ?? 0);
  const chargeableChildCount = (bookingPolicy?.extra_child_rate ?? 0) > 0
    ? checkInChildAges.filter((age) => age >= (bookingPolicy?.child_free_under_age ?? 0)).length
    : 0;
  const extraChildCharge = chargeableChildCount * (bookingPolicy?.extra_child_rate ?? 0);
  const occupancySurchargePerNight = extraAdultCharge + extraChildCharge;
  const estimatedNightlyRate = (room?.rate_per_night ?? 0) + occupancySurchargePerNight;
  const estimatedCheckInTotal = estimatedNightlyRate * checkInNights;

  // Nights and the two datetime pickers are kept in sync so exactly ONE of them is ever the
  // "driver" at a time — nights is authoritative by default (arrival + nights determines
  // departure, at the property's configured checkout time), but manually editing the departure
  // date instead re-derives nights from it. This replaced a previous bug: handleCheckIn used to
  // silently recompute nights from the raw millisecond gap between arrival/departure whenever
  // BOTH happened to be set, which (a) overrode an explicit Nights value the staff had just
  // typed and (b) used Math.ceil on a partial-day duration, over-counting by a night whenever
  // the two times of day didn't line up exactly (e.g. a 2-night stay reading as 3 nights on the
  // folio). Nights is now always calendar-day arithmetic and always the value actually charged.
  function calendarDaysBetween(a: Date, b: Date): number {
    const aMid = new Date(a.getFullYear(), a.getMonth(), a.getDate()).getTime();
    const bMid = new Date(b.getFullYear(), b.getMonth(), b.getDate()).getTime();
    return Math.round((bMid - aMid) / 86_400_000);
  }
  function toDatetimeLocalValue(d: Date): string {
    const pad = (n: number) => String(n).padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
  }
  function departureFromNights(arrivalBase: Date, nights: number): Date {
    const [h, m] = checkoutTimeDefault.split(':').map((x) => parseInt(x, 10));
    const out = new Date(arrivalBase.getFullYear(), arrivalBase.getMonth(), arrivalBase.getDate() + nights);
    out.setHours(Number.isFinite(h) ? h : 10, Number.isFinite(m) ? m : 0, 0, 0);
    return out;
  }
  function setNights(value: string) {
    setCheckInForm((f) => {
      const n = Math.max(1, parseInt(value) || 1);
      const arrivalBase = f.expected_arrival_at ? new Date(f.expected_arrival_at) : new Date();
      return { ...f, nights: value, expected_departure_at: toDatetimeLocalValue(departureFromNights(arrivalBase, n)) };
    });
  }
  function setArrival(value: string) {
    setCheckInForm((f) => {
      if (!value) return { ...f, expected_arrival_at: value };
      const n = Math.max(1, parseInt(f.nights) || 1);
      return { ...f, expected_arrival_at: value, expected_departure_at: toDatetimeLocalValue(departureFromNights(new Date(value), n)) };
    });
  }
  function setDeparture(value: string) {
    setCheckInForm((f) => {
      if (!value) return { ...f, expected_departure_at: value };
      const arrivalBase = f.expected_arrival_at ? new Date(f.expected_arrival_at) : new Date();
      const n = Math.max(1, calendarDaysBetween(arrivalBase, new Date(value)));
      return { ...f, expected_departure_at: value, nights: String(n) };
    });
  }

  // Auto-fill departure the first time the check-in form opens, so the field shows a real
  // computed value (today + 1 night, at the configured checkout time) instead of sitting blank
  // until the staff happens to touch Nights.
  useEffect(() => {
    if (showCheckIn && !checkInForm.expected_departure_at) {
      setNights(checkInForm.nights);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [showCheckIn]);

  const canCheckIn = !!room && !CHECK_IN_BLOCKED_STATUSES.has(room.status);
  const updateRoomStatus = useUpdateRoomStatus(roomId);
  async function handleMarkAvailable() {
    try {
      await updateRoomStatus.mutateAsync('available');
      toast.success('Room marked available');
    } catch (e) {
      toast.error(await apiErrorMessage(e, 'Failed to update room status'));
    }
  }

  const checkIn  = useCheckIn(roomId);
  const checkOut = useCheckOut(roomId);
  const lateCheckout = useLateCheckout(roomId);
  const [showLate, setShowLate] = useState(false);
  const [lateForm, setLateForm] = useState({ surcharge_amount: 0, notes: '' });

  // Manual folio charge (minibar / room service / damage). When an inventory SKU is given
  // the backend backflushes its stock (a recipe SKU explodes its BOM); leave it blank for
  // a pure money charge.
  const postCharge = usePostFolioCharge(roomId);
  const [showCharge, setShowCharge] = useState(false);
  const [chargeForm, setChargeForm] = useState({ description: '', amount: '', charge_type: 'food', inventory_sku: '', quantity: '1' });

  function submitCharge() {
    const amount = parseFloat(chargeForm.amount);
    if (!chargeForm.description.trim() || !amount || amount <= 0) {
      toast.error('Enter a description and a positive amount');
      return;
    }
    postCharge.mutate(
      {
        description: chargeForm.description.trim(),
        amount,
        charge_type: chargeForm.charge_type,
        ...(chargeForm.inventory_sku.trim()
          ? { inventory_sku: chargeForm.inventory_sku.trim(), quantity: parseFloat(chargeForm.quantity) || 1 }
          : {}),
      },
      {
        onSuccess: () => {
          toast.success('Charge added to folio');
          setChargeForm({ description: '', amount: '', charge_type: 'food', inventory_sku: '', quantity: '1' });
          setShowCharge(false);
        },
        onError: async (e) => toast.error(await apiErrorMessage(e, 'Failed to add charge')),
      },
    );
  }

  async function handleLateCheckout() {
    try {
      await lateCheckout.mutateAsync({ surcharge_amount: lateForm.surcharge_amount, notes: lateForm.notes || undefined });
      toast.success('Late checkout approved');
      setShowLate(false);
      setLateForm({ surcharge_amount: 0, notes: '' });
    } catch (e) {
      toast.error(await apiErrorMessage(e, 'Failed to approve late checkout'));
    }
  }

  async function handleCheckIn() {
    const f = checkInForm;
    const guestName = `${f.first_name} ${f.last_name}`.trim() || f.first_name;
    if (!guestName) { toast.error('Guest name is required'); return; }
    if (!f.phone.trim()) { toast.error('Phone number is required'); return; }
    if (!f.id_number.trim()) { toast.error('ID number is required'); return; }
    if (requiresUpfrontPayment && !checkInPaymentMethod) {
      toast.error('This property requires payment at check-in — select a payment method');
      return;
    }

    // Nights is always the authoritative value here — setNights/setArrival/setDeparture keep it
    // in sync with whichever field the staff actually edited, using calendar-day arithmetic (see
    // their doc comment). Previously this re-derived nights from the raw millisecond gap between
    // the two datetime pickers, which silently overrode an explicit Nights value and, via
    // Math.ceil, over-counted by a night whenever the two times of day didn't line up exactly.
    const nights = Math.max(1, parseInt(f.nights) || 1);
    const childrenCount = parseInt(f.children) || 0;
    const childAges = f.child_ages.split(',').map((s) => parseInt(s.trim(), 10)).filter((n) => Number.isFinite(n) && n >= 0);
    try {
      const res = await checkIn.mutateAsync({
        guest_name: guestName,
        first_name: f.first_name || undefined,
        last_name: f.last_name || undefined,
        email: f.email || undefined,
        phone: f.phone,
        nationality: f.nationality || undefined,
        id_type: f.id_type || undefined,
        id_number: f.id_number,
        id_document_url: f.id_document_url || undefined,
        adults: parseInt(f.adults) || 1,
        children: childrenCount,
        child_ages: childAges.length > 0 ? childAges : undefined,
        nights,
        expected_arrival_at: f.expected_arrival_at ? new Date(f.expected_arrival_at).toISOString() : undefined,
        expected_departure_at: f.expected_departure_at ? new Date(f.expected_departure_at).toISOString() : undefined,
        source: 'staff',
        ...(requiresUpfrontPayment
          ? { payment_method: checkInPaymentMethod, payment_reference: checkInPaymentReference.trim() || undefined }
          : {}),
      });
      if (res.payment_timing === 'pay_upfront' && !res.payment_recorded) {
        toast.warning('Guest checked in, but the payment could not be recorded — collect it via Checkout & Settle Bill.');
      } else {
        toast.success('Guest checked in');
      }
      setShowCheckIn(false);
      setCheckInPaymentMethod('');
      setCheckInPaymentReference('');
      // Redirect straight to checkout so the desk can see/settle the bill (room charge already posted).
      setShowCheckout(true);
    } catch (e) {
      toast.error(await apiErrorMessage(e, 'Check-in failed'));
    }
  }

  async function handleCheckOut() {
    try {
      await checkOut.mutateAsync();
      toast.success('Guest checked out');
      router.push(`/${orgSlug}/hotel/rooms`);
    } catch (e) {
      toast.error(await apiErrorMessage(e, 'Check-out failed'));
    }
  }

  if (roomLoading || !room) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  const showEmptyState = !isOccupied && !showCheckIn;

  return (
    <div className="mx-auto w-full max-w-6xl space-y-6 p-4 sm:p-6 lg:px-8">
      <div className="flex items-center gap-3">
        <Link
          href={`/${orgSlug}/hotel/rooms`}
          aria-label="Back to rooms"
          className="p-2 rounded-lg hover:bg-muted transition-colors shrink-0"
        >
          <ArrowLeft className="h-5 w-5" />
        </Link>
        <div className="flex items-center gap-3 min-w-0">
          <div className="size-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
            <BedDouble className="h-5 w-5 text-primary" />
          </div>
          <div className="min-w-0">
            <h1 className="text-xl font-bold text-foreground truncate">Room {room.room_number}</h1>
            <p className="text-sm text-muted-foreground capitalize truncate">{room.room_type.replace('_', ' ')} · Floor {room.floor}</p>
          </div>
        </div>
        <span className={cn(
          'ml-auto shrink-0 text-xs px-3 py-1 rounded-full font-semibold capitalize',
          room.status === 'available' ? 'bg-green-500/10 text-green-700' :
          room.status === 'occupied' ? 'bg-red-500/10 text-red-700' :
          'bg-muted text-muted-foreground'
        )}>
          {room.status}
        </span>
      </div>

      {/* Check-in form — full width while open; it's the only content on the page at this
          point (an available room has no guest/folio to show yet), so a sidebar next to it
          would just be empty space. */}
      {showCheckIn && (
        <Card>
          <CardContent className="p-5 sm:p-6 space-y-5">
            <p className="font-semibold text-foreground">Guest Check-In</p>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
              <Field label="First Name *" value={checkInForm.first_name} onChange={(v) => setField('first_name', v)} placeholder="First name" />
              <Field label="Last Name" value={checkInForm.last_name} onChange={(v) => setField('last_name', v)} placeholder="Last name" />
              <Field label="Phone *" value={checkInForm.phone} onChange={(v) => setField('phone', v)} placeholder="+254..." />
              <Field label="Email" type="email" value={checkInForm.email} onChange={(v) => setField('email', v)} placeholder="guest@email.com" />
              <Field label="Nationality" value={checkInForm.nationality} onChange={(v) => setField('nationality', v)} placeholder="e.g. Kenyan" />
              <label className="block">
                <span className="text-sm font-medium text-foreground">ID Type</span>
                <select
                  value={checkInForm.id_type}
                  onChange={(e) => setField('id_type', e.target.value)}
                  className="mt-1 w-full px-4 py-2.5 rounded-xl border border-input bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                >
                  <option value="national_id">National ID</option>
                  <option value="passport">Passport</option>
                  <option value="driving_licence">Driving Licence</option>
                  <option value="other">Other</option>
                </select>
              </label>
              <Field label="ID Number *" value={checkInForm.id_number} onChange={(v) => setField('id_number', v)} placeholder="Required — guest ID/passport number" />
              <Field label="ID Document URL" value={checkInForm.id_document_url} onChange={(v) => setField('id_document_url', v)} placeholder="Uploaded scan link (optional)" />
              <Field label="Nights" type="number" value={checkInForm.nights} onChange={setNights} placeholder="1" />
              <Field label="Check-In Date & Time" type="datetime-local" value={checkInForm.expected_arrival_at} onChange={setArrival} />
              <Field label="Check-Out Date & Time" type="datetime-local" value={checkInForm.expected_departure_at} onChange={setDeparture} />
              <Field label="Adults" type="number" value={checkInForm.adults} onChange={(v) => setField('adults', v)} placeholder="1" />
              <Field label="Children" type="number" value={checkInForm.children} onChange={(v) => setField('children', v)} placeholder="0" />
              <Field label="Child Ages (comma-separated)" value={checkInForm.child_ages} onChange={(v) => setField('child_ages', v)} placeholder="e.g. 4, 9" />
            </div>

            <p className="text-[11px] text-muted-foreground">
              Check-out auto-fills to {checkInNights} night{checkInNights !== 1 ? 's' : ''} from check-in, by {checkoutTimeDefault} on the departure date (this property&apos;s standard checkout time) — edit either field directly and the other stays in sync. A later departure can still be approved afterwards via Late Checkout.
            </p>

            {baseOccupancyAdults > 0 && (
              <div className="rounded-xl bg-muted/50 px-3 py-2 space-y-1">
                <div className="flex items-center justify-between text-sm">
                  <span className="text-muted-foreground">Estimated room total ({checkInNights} night{checkInNights !== 1 ? 's' : ''})</span>
                  <span className="font-bold text-foreground tabular-nums">{formatCurrency(estimatedCheckInTotal, currency)}</span>
                </div>
                {occupancySurchargePerNight > 0 && (
                  <p className="text-[11px] text-muted-foreground">
                    {formatCurrency(room?.rate_per_night ?? 0, currency)} base rate
                    {extraAdultCount > 0 && ` + ${extraAdultCount} extra adult${extraAdultCount !== 1 ? 's' : ''} (${formatCurrency(extraAdultCharge, currency)})`}
                    {chargeableChildCount > 0 && ` + ${chargeableChildCount} chargeable child${chargeableChildCount !== 1 ? 'ren' : ''} (${formatCurrency(extraChildCharge, currency)})`}
                    {' '}per night, beyond {baseOccupancyAdults} adult{baseOccupancyAdults !== 1 ? 's' : ''} included free.
                  </p>
                )}
              </div>
            )}

            {paymentTiming === 'per_day_split' && (
              <p className="text-xs text-muted-foreground rounded-xl bg-muted/50 px-3 py-2">
                This property bills per night — only the first night is charged now; the remaining {Math.max(checkInNights - 1, 0)} night{checkInNights - 1 !== 1 ? 's' : ''} post automatically to the folio as each day of the stay occurs.
              </p>
            )}

            {requiresUpfrontPayment && (
              <div className="rounded-xl border border-primary/30 bg-primary/5 p-4 space-y-3 sm:max-w-md">
                <div className="flex items-center justify-between">
                  <p className="text-sm font-semibold text-foreground">Collect Payment (required at check-in)</p>
                  {estimatedCheckInTotal > 0 && (
                    <span className="text-sm font-bold text-primary tabular-nums">~{formatCurrency(estimatedCheckInTotal, currency)}</span>
                  )}
                </div>
                <HotelTenderPicker value={checkInPaymentMethod} onChange={setCheckInPaymentMethod} />
                <label className="block">
                  <span className="text-xs font-medium text-muted-foreground">Reference (optional — M-Pesa code / card approval)</span>
                  <input
                    value={checkInPaymentReference}
                    onChange={(e) => setCheckInPaymentReference(e.target.value.toUpperCase())}
                    placeholder="Code / approval"
                    className="mt-1 w-full px-3 py-2 rounded-lg border border-input bg-background text-sm uppercase focus:outline-none focus:ring-2 focus:ring-ring"
                  />
                </label>
              </div>
            )}

            <div className="flex gap-3 pt-1 sm:max-w-md">
              <button onClick={() => setShowCheckIn(false)} className="flex-1 sm:flex-none sm:px-8 py-2.5 rounded-xl border border-border text-foreground font-medium hover:bg-muted transition-colors">
                Cancel
              </button>
              <button
                onClick={handleCheckIn}
                disabled={checkIn.isPending || !checkInForm.first_name.trim() || !checkInForm.phone.trim() || !checkInForm.id_number.trim() || (requiresUpfrontPayment && !checkInPaymentMethod)}
                className="flex-1 py-2.5 rounded-xl bg-primary text-primary-foreground font-semibold hover:bg-primary/90 disabled:opacity-50 transition-colors"
              >
                {checkIn.isPending ? 'Checking in…' : 'Confirm Check-In'}
              </button>
            </div>
          </CardContent>
        </Card>
      )}

      {!showCheckIn && (
      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        {/* Main column — guest info, folio, add-charge */}
        <div className="space-y-6 lg:col-span-2">
          {/* Guest info */}
          {isOccupied && guest && (
            <Card>
              <CardContent className="p-5 space-y-3">
                <p className="text-xs font-semibold uppercase text-muted-foreground tracking-wider">Current Guest</p>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 text-sm">
                  {[
                    { label: 'Name', value: [guest.first_name, guest.last_name].filter(Boolean).join(' ') || guest.guest_name },
                    { label: 'Email', value: guest.email || '—' },
                    { label: 'Phone', value: guest.phone },
                    { label: 'Nationality', value: guest.nationality || '—' },
                    { label: guest.id_type ? guest.id_type.replace('_', ' ').replace(/\b\w/g, (c) => c.toUpperCase()) : 'ID', value: guest.id_number },
                    { label: 'Guests', value: `${guest.adults ?? 1} adult(s)${(guest.children ?? 0) > 0 ? `, ${guest.children} child(ren)` : ''}` },
                    { label: 'Check-In', value: new Date(guest.expected_arrival_at || guest.check_in_date).toLocaleString() },
                    { label: 'Check-Out', value: new Date(guest.expected_departure_at || guest.check_out_date).toLocaleString() },
                    { label: 'Nights', value: String(guest.nights) },
                    { label: 'Room Total', value: formatCurrency(guest.total_room_charge, currency), highlight: true },
                  ].map(({ label, value, highlight }) => (
                    <div key={label} className="min-w-0">
                      <p className="text-muted-foreground">{label}</p>
                      <p className={cn('font-semibold truncate', highlight ? 'text-primary' : 'text-foreground')}>{value}</p>
                    </div>
                  ))}
                </div>
                {guest.id_document_url && (
                  <a href={guest.id_document_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-xs text-primary hover:underline">
                    <Receipt className="h-3 w-3" /> View ID document
                  </a>
                )}
              </CardContent>
            </Card>
          )}

          {/* Folio */}
          {isOccupied && folio.length > 0 && (
            <Card>
              <CardContent className="p-5 space-y-3">
                <div className="flex items-center gap-2">
                  <Receipt className="h-4 w-4 text-muted-foreground" />
                  <p className="text-xs font-semibold uppercase text-muted-foreground tracking-wider">Room Folio</p>
                </div>
                <ul className="divide-y divide-border">
                  {folio.map((item) => (
                    <li key={item.id} className="flex items-center justify-between gap-4 py-2.5 text-sm">
                      <div className="min-w-0">
                        <p className="font-medium text-foreground truncate">{item.description}</p>
                        <p className="text-xs text-muted-foreground capitalize">
                          {item.charge_type.replace('_', ' ')}
                          {item.inventory_sku ? ` · ${item.inventory_sku}` : ''}
                        </p>
                      </div>
                      <p className="font-semibold text-foreground shrink-0 tabular-nums">{formatCurrency(item.amount, currency)}</p>
                    </li>
                  ))}
                </ul>
                <div className="flex items-center justify-between pt-2 border-t border-border font-bold text-foreground">
                  <span>Total</span>
                  <span className="text-primary tabular-nums">{formatCurrency(folio.reduce((s, i) => s + i.amount, 0), currency)}</span>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Manual folio charge (minibar / room service / damage); an inventory SKU deducts stock */}
          {isOccupied && (
            <Card>
              <CardContent className="p-4 sm:p-5">
                {!showCharge ? (
                  <button
                    onClick={() => setShowCharge(true)}
                    className="w-full py-2.5 rounded-xl border border-dashed border-border text-sm text-muted-foreground hover:bg-muted hover:border-primary/40 transition-colors"
                  >
                    + Add folio charge (minibar / room service / damage)
                  </button>
                ) : (
                  <div className="space-y-4">
                    <p className="text-xs font-semibold uppercase text-muted-foreground tracking-wider">Add Folio Charge</p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
                      <label className="block sm:col-span-2 lg:col-span-2">
                        <span className="text-xs font-medium text-muted-foreground">Description</span>
                        <input
                          className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
                          placeholder="e.g. Minibar - Coke"
                          value={chargeForm.description}
                          onChange={(e) => setChargeForm((f) => ({ ...f, description: e.target.value }))}
                        />
                      </label>
                      <label className="block">
                        <span className="text-xs font-medium text-muted-foreground">Amount</span>
                        <input
                          type="number" min="0" step="0.01"
                          className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
                          placeholder="0.00"
                          value={chargeForm.amount}
                          onChange={(e) => setChargeForm((f) => ({ ...f, amount: e.target.value }))}
                        />
                      </label>
                      <label className="block">
                        <span className="text-xs font-medium text-muted-foreground">Type</span>
                        <select
                          className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
                          value={chargeForm.charge_type}
                          onChange={(e) => setChargeForm((f) => ({ ...f, charge_type: e.target.value }))}
                        >
                          {CHARGE_TYPES.map((t) => (
                            <option key={t.value} value={t.value}>{t.label}</option>
                          ))}
                        </select>
                      </label>
                      <label className="block sm:col-span-2 lg:col-span-2">
                        <span className="text-xs font-medium text-muted-foreground">Inventory SKU (optional — deducts stock)</span>
                        <input
                          className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-ring"
                          placeholder="SKU"
                          value={chargeForm.inventory_sku}
                          onChange={(e) => setChargeForm((f) => ({ ...f, inventory_sku: e.target.value }))}
                        />
                      </label>
                      {chargeForm.inventory_sku.trim() && (
                        <label className="block">
                          <span className="text-xs font-medium text-muted-foreground">Qty</span>
                          <input
                            type="number" min="1" step="1"
                            className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
                            value={chargeForm.quantity}
                            onChange={(e) => setChargeForm((f) => ({ ...f, quantity: e.target.value }))}
                          />
                        </label>
                      )}
                    </div>
                    <div className="flex gap-3">
                      <button onClick={() => setShowCharge(false)} className="flex-1 py-2.5 rounded-xl border border-border text-sm font-medium hover:bg-muted transition-colors">Cancel</button>
                      <button
                        onClick={submitCharge}
                        disabled={postCharge.isPending}
                        className="flex-1 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm font-semibold hover:bg-primary/90 disabled:opacity-50 transition-colors"
                      >
                        {postCharge.isPending ? 'Adding...' : 'Add Charge'}
                      </button>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          )}

          {/* Last guest — shown once the room is no longer occupied but recently had a stay
              (e.g. straight out of checkout, while status is "cleaning"), so front desk /
              housekeeping can still see who was just there for a damage report or lost-item
              claim raised after the fact. */}
          {!isOccupied && lastGuest && (
            <Card>
              <CardContent className="p-5 space-y-2">
                <p className="text-xs font-semibold uppercase text-muted-foreground tracking-wider">Last Guest</p>
                <div className="flex items-center justify-between text-sm">
                  <div>
                    <p className="font-semibold text-foreground">{[lastGuest.first_name, lastGuest.last_name].filter(Boolean).join(' ') || lastGuest.guest_name}</p>
                    <p className="text-xs text-muted-foreground">{lastGuest.phone}</p>
                  </div>
                  <p className="text-xs text-muted-foreground">
                    Checked out {lastGuest.checked_out_at ? new Date(lastGuest.checked_out_at).toLocaleString() : '—'}
                  </p>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Empty state — status-aware: "available" is the only status that can misleadingly
              read as ready-to-book if the actual status (cleaning/maintenance/reserved) isn't
              called out explicitly. */}
          {showEmptyState && (
            <div className="flex flex-col items-center justify-center gap-3 rounded-2xl border border-dashed border-border py-16 text-center text-muted-foreground">
              <div className="size-14 rounded-2xl bg-primary/10 flex items-center justify-center">
                <BedDouble className="h-7 w-7 text-primary" />
              </div>
              <p className="font-medium text-foreground">{ROOM_STATUS_COPY[room.status]?.title ?? 'This room is available'}</p>
              <p className="text-sm max-w-xs">{ROOM_STATUS_COPY[room.status]?.body ?? 'Check in a guest to open their stay, post room charges, and start the folio.'}</p>
              {(room.status === 'cleaning' || room.status === 'maintenance') && (
                <button
                  onClick={handleMarkAvailable}
                  disabled={updateRoomStatus.isPending}
                  className="mt-2 text-xs font-semibold text-primary hover:underline disabled:opacity-50"
                >
                  {updateRoomStatus.isPending ? 'Updating…' : 'Mark room available now'}
                </button>
              )}
            </div>
          )}
        </div>

        {/* Sidebar — primary actions, sticky on desktop */}
        <div className="lg:col-span-1">
          <div className="space-y-3 lg:sticky lg:top-6">
            {!isOccupied && !showCheckIn && (
              <button
                onClick={() => setShowCheckIn(true)}
                disabled={!canCheckIn}
                title={canCheckIn ? undefined : `Room is ${room.status} — mark it available first`}
                className="w-full flex items-center justify-center gap-2 py-3 rounded-xl bg-primary text-primary-foreground font-semibold hover:bg-primary/90 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
              >
                <LogIn className="h-5 w-5" /> Check In Guest
              </button>
            )}

            {isOccupied && (
              <div className="space-y-3">
                <button
                  onClick={() => setShowEditGuest(true)}
                  className="w-full flex items-center justify-center gap-2 py-3 rounded-xl border border-border font-semibold hover:bg-muted transition-colors"
                >
                  <Pencil className="h-5 w-5" />
                  Edit Guest / Booking
                </button>
                {/* Settle Now — take a payment without ending the stay (e.g. a settle_at_checkout
                    guest who didn't pay at check-in). Opens the SAME panel as Checkout & Settle
                    Bill, just with "check out when balance clears" unchecked by default. */}
                <button
                  onClick={() => { setCheckoutPanelDefaultsToCheckout(false); setShowCheckout(true); }}
                  className="w-full flex items-center justify-center gap-2 py-3 rounded-xl border-2 border-primary text-primary font-bold hover:bg-primary/10 transition-colors"
                >
                  <Wallet className="h-5 w-5" />
                  Settle Now
                </button>
                <button
                  onClick={() => { setCheckoutPanelDefaultsToCheckout(true); setShowCheckout(true); }}
                  className="w-full flex items-center justify-center gap-2 py-3 rounded-xl bg-primary text-primary-foreground font-bold hover:bg-primary/90 transition-colors"
                >
                  <Receipt className="h-5 w-5" />
                  Checkout &amp; Settle Bill
                </button>
                <button
                  onClick={() => setShowLate(true)}
                  className="w-full flex items-center justify-center gap-2 py-3 rounded-xl border border-border font-semibold hover:bg-muted transition-colors"
                >
                  <Clock className="h-5 w-5" />
                  Late Checkout
                </button>
                <button
                  onClick={handleCheckOut}
                  disabled={checkOut.isPending}
                  className="w-full flex items-center justify-center gap-2 py-3 rounded-xl border border-destructive/40 text-destructive font-semibold hover:bg-destructive/5 disabled:opacity-50 transition-colors"
                >
                  {checkOut.isPending ? <Loader2 className="h-5 w-5 animate-spin" /> : <LogOut className="h-5 w-5" />}
                  Check Out (no payment)
                </button>
              </div>
            )}

            {/* Report Damage — available regardless of occupancy (housekeeping may find it
                after the guest has already checked out); goes to a manager for review, never
                straight to the folio. */}
            <button
              onClick={() => setShowDamageReport(true)}
              className="w-full flex items-center justify-center gap-2 py-2.5 rounded-xl border border-amber-500/30 text-amber-700 dark:text-amber-400 text-sm font-semibold hover:bg-amber-500/10 transition-colors"
            >
              <ShieldAlert className="h-4 w-4" />
              Report Damage
            </button>

            {/* Log Found Item — same "available regardless of occupancy" reasoning as damage
                reports: most finds happen during post-checkout cleaning, when the room has
                already gone back to "cleaning"/available and lastGuest is who it belonged to. */}
            <button
              onClick={() => setShowLostFound(true)}
              className="w-full flex items-center justify-center gap-2 py-2.5 rounded-xl border border-blue-500/30 text-blue-700 dark:text-blue-400 text-sm font-semibold hover:bg-blue-500/10 transition-colors"
            >
              <PackageSearch className="h-4 w-4" />
              Log Found Item
            </button>
          </div>
        </div>
      </div>
      )}

      <DamageReportModal
        roomId={roomId}
        roomNumber={room.room_number}
        open={showDamageReport}
        onClose={() => setShowDamageReport(false)}
      />

      <LostFoundModal
        outletId={room.outlet_id}
        roomId={roomId}
        roomGuestId={(guest ?? lastGuest)?.id}
        roomLabel={room.room_number}
        open={showLostFound}
        onClose={() => setShowLostFound(false)}
      />

      <CheckoutPanel
        roomId={roomId}
        open={showCheckout}
        onClose={() => setShowCheckout(false)}
        onCheckedOut={() => router.push(`/${orgSlug}/hotel/rooms`)}
        defaultCheckoutOnSettle={checkoutPanelDefaultsToCheckout}
      />

      {guest && (
        <EditGuestModal
          roomId={roomId}
          guest={guest}
          open={showEditGuest}
          onClose={() => setShowEditGuest(false)}
        />
      )}

      {showLate && (
        <div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center bg-black/50 backdrop-blur-sm p-0 sm:p-4" onClick={() => setShowLate(false)}>
          <div className="w-full max-w-sm sm:rounded-2xl rounded-t-2xl bg-card border border-border shadow-2xl" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between px-5 py-4 border-b border-border">
              <h2 className="text-base font-bold text-foreground">Approve Late Checkout</h2>
              <button type="button" aria-label="Close" onClick={() => setShowLate(false)} className="h-8 w-8 rounded-full bg-muted flex items-center justify-center hover:bg-destructive/10 hover:text-destructive transition-colors">
                <X className="h-4 w-4" />
              </button>
            </div>
            <div className="p-5 space-y-4">
              <label className="block">
                <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Surcharge Amount ({currency})</span>
                <input
                  type="number" min={0} step={0.01}
                  value={lateForm.surcharge_amount}
                  onChange={(e) => setLateForm((f) => ({ ...f, surcharge_amount: parseFloat(e.target.value) || 0 }))}
                  className="mt-1.5 w-full px-3 py-2.5 rounded-xl border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring"
                />
              </label>
              <label className="block">
                <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Notes (optional)</span>
                <input
                  value={lateForm.notes}
                  onChange={(e) => setLateForm((f) => ({ ...f, notes: e.target.value }))}
                  placeholder="e.g. 2pm departure agreed"
                  className="mt-1.5 w-full px-3 py-2.5 rounded-xl border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring"
                />
              </label>
              <p className="text-[11px] text-muted-foreground">The surcharge (if any) is posted to the guest&apos;s folio.</p>
              <div className="flex gap-3 pt-1">
                <button type="button" onClick={() => setShowLate(false)} className="flex-1 py-2.5 rounded-xl border border-border text-sm font-medium hover:bg-muted transition-colors">Cancel</button>
                <button
                  onClick={handleLateCheckout}
                  disabled={lateCheckout.isPending}
                  className="flex-1 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm font-semibold hover:bg-primary/90 disabled:opacity-50 transition-colors"
                >
                  {lateCheckout.isPending ? <Loader2 className="h-4 w-4 animate-spin mx-auto" /> : 'Approve'}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function Field({ label, value, onChange, placeholder, type = 'text' }: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
  type?: string;
}) {
  return (
    <label className="block">
      <span className="text-sm font-medium text-foreground">{label}</span>
      <input
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        className="mt-1 w-full px-4 py-2.5 rounded-xl border border-input bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
      />
    </label>
  );
}

export default function RoomDetailPage() {
  return (
    <ModuleGate moduleKey="hotel" fallback={<ModuleUnavailablePage moduleKey="hotel" />}>
      <FeatureGate feature="hotel_module" fallback={<FeatureLocked feature="hotel_module" label="Hotel & Rooms" />}>
        <RoomDetailPageInner />
      </FeatureGate>
    </ModuleGate>
  );
}
