'use client';

import { useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useHotelRoom, useRoomFolio, useCheckIn, useCheckOut, useLateCheckout, usePostFolioCharge, useBookingPolicy } from '@/hooks/useHotel';
import { Card, CardContent } from '@/components/ui/base';
import { cn, formatCurrency } from '@/lib/utils';
import {
  ArrowLeft,
  Banknote,
  BedDouble,
  Clock,
  CreditCard,
  Loader2,
  LogIn,
  LogOut,
  Receipt,
  Smartphone,
  X,
} from 'lucide-react';
import Link from 'next/link';
import { toast } from 'sonner';
import { apiErrorMessage } from '@/lib/api/error-message';
import { ModuleGate } from '@/components/auth/module-gate';
import { ModuleUnavailablePage } from '@/components/auth/module-unavailable';
import { CheckoutPanel } from '@/components/pos/hotel/checkout-panel';

// Folio charge types a front-desk agent can post manually from this form. Mirrors the
// subset of pos-api's RoomFolioItem.charge_type enum that isn't already posted by a
// dedicated flow elsewhere (room_charge = auto at check-in, amenity/facility = their own
// charge buttons, late_checkout = the Late Checkout action, conference/meal_voucher =
// generated by the conference module).
const CHARGE_TYPES = [
  { value: 'food', label: 'Food' },
  { value: 'minibar', label: 'Minibar' },
  { value: 'laundry', label: 'Laundry' },
  { value: 'room_service', label: 'Room Service' },
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'damage', label: 'Damage / Fine' },
  { value: 'other', label: 'Other' },
];

const CHECK_IN_PAYMENT_METHODS: { key: string; label: string; icon: React.ElementType }[] = [
  { key: 'cash', label: 'Cash', icon: Banknote },
  { key: 'card_manual', label: 'Card / PDQ', icon: CreditCard },
  { key: 'mpesa', label: 'M-Pesa', icon: Smartphone },
];

function RoomDetailPageInner() {
  const params = useParams();
  const orgSlug = params?.orgSlug as string;
  const roomId = params?.roomId as string;
  const router = useRouter();

  const [checkInForm, setCheckInForm] = useState({
    first_name: '', last_name: '', email: '', phone: '',
    nationality: '', id_type: 'national_id', id_number: '', id_document_url: '',
    adults: '1', children: '0',
    expected_arrival_at: '', expected_departure_at: '', nights: '1',
  });
  const [showCheckIn, setShowCheckIn] = useState(false);
  const [showCheckout, setShowCheckout] = useState(false);
  const [checkInPaymentMethod, setCheckInPaymentMethod] = useState('');
  const [checkInPaymentReference, setCheckInPaymentReference] = useState('');

  function setField(key: keyof typeof checkInForm, value: string) {
    setCheckInForm((f) => ({ ...f, [key]: value }));
  }

  const { data: room, isLoading: roomLoading } = useHotelRoom(roomId);
  const currency = room?.currency ?? 'KES';
  const isOccupied = room?.status === 'occupied';
  const guest = room?.edges?.guests?.[0] ?? null;
  const { data: folio = [] } = useRoomFolio(roomId, isOccupied);
  const { data: bookingPolicy } = useBookingPolicy();
  const paymentTiming = bookingPolicy?.payment_timing ?? 'settle_at_checkout';
  const requiresUpfrontPayment = paymentTiming === 'pay_upfront';
  const checkInNights = parseInt(checkInForm.nights) || 1;
  const estimatedCheckInTotal = (room?.rate_per_night ?? 0) * checkInNights;

  const checkIn  = useCheckIn(roomId);
  const checkOut = useCheckOut(roomId);
  const lateCheckout = useLateCheckout(roomId);
  const [showLate, setShowLate] = useState(false);
  const [lateForm, setLateForm] = useState({ surcharge_amount: 0, notes: '' });

  // Manual folio charge (minibar / room service / damage). When an inventory SKU is given
  // the backend backflushes its stock (a recipe SKU explodes its BOM); leave it blank for
  // a pure money charge.
  const postCharge = usePostFolioCharge(roomId);
  const [showCharge, setShowCharge] = useState(false);
  const [chargeForm, setChargeForm] = useState({ description: '', amount: '', charge_type: 'food', inventory_sku: '', quantity: '1' });

  function submitCharge() {
    const amount = parseFloat(chargeForm.amount);
    if (!chargeForm.description.trim() || !amount || amount <= 0) {
      toast.error('Enter a description and a positive amount');
      return;
    }
    postCharge.mutate(
      {
        description: chargeForm.description.trim(),
        amount,
        charge_type: chargeForm.charge_type,
        ...(chargeForm.inventory_sku.trim()
          ? { inventory_sku: chargeForm.inventory_sku.trim(), quantity: parseFloat(chargeForm.quantity) || 1 }
          : {}),
      },
      {
        onSuccess: () => {
          toast.success('Charge added to folio');
          setChargeForm({ description: '', amount: '', charge_type: 'food', inventory_sku: '', quantity: '1' });
          setShowCharge(false);
        },
        onError: async (e) => toast.error(await apiErrorMessage(e, 'Failed to add charge')),
      },
    );
  }

  async function handleLateCheckout() {
    try {
      await lateCheckout.mutateAsync({ surcharge_amount: lateForm.surcharge_amount, notes: lateForm.notes || undefined });
      toast.success('Late checkout approved');
      setShowLate(false);
      setLateForm({ surcharge_amount: 0, notes: '' });
    } catch (e) {
      toast.error(await apiErrorMessage(e, 'Failed to approve late checkout'));
    }
  }

  async function handleCheckIn() {
    const f = checkInForm;
    const guestName = `${f.first_name} ${f.last_name}`.trim() || f.first_name;
    if (!guestName) { toast.error('Guest name is required'); return; }
    if (requiresUpfrontPayment && !checkInPaymentMethod) {
      toast.error('This property requires payment at check-in — select a payment method');
      return;
    }

    // Derive nights from the date pickers when both are provided.
    let nights = parseInt(f.nights) || 1;
    if (f.expected_arrival_at && f.expected_departure_at) {
      const ms = new Date(f.expected_departure_at).getTime() - new Date(f.expected_arrival_at).getTime();
      const d = Math.ceil(ms / 86_400_000);
      if (d > 0) nights = d;
    }
    const childrenCount = parseInt(f.children) || 0;
    try {
      const res = await checkIn.mutateAsync({
        guest_name: guestName,
        first_name: f.first_name || undefined,
        last_name: f.last_name || undefined,
        email: f.email || undefined,
        phone: f.phone,
        nationality: f.nationality || undefined,
        id_type: f.id_type || undefined,
        id_number: f.id_number,
        id_document_url: f.id_document_url || undefined,
        adults: parseInt(f.adults) || 1,
        children: childrenCount,
        nights,
        expected_arrival_at: f.expected_arrival_at ? new Date(f.expected_arrival_at).toISOString() : undefined,
        expected_departure_at: f.expected_departure_at ? new Date(f.expected_departure_at).toISOString() : undefined,
        source: 'staff',
        ...(requiresUpfrontPayment
          ? { payment_method: checkInPaymentMethod, payment_reference: checkInPaymentReference.trim() || undefined }
          : {}),
      });
      if (res.payment_timing === 'pay_upfront' && !res.payment_recorded) {
        toast.warning('Guest checked in, but the payment could not be recorded — collect it via Checkout & Settle Bill.');
      } else {
        toast.success('Guest checked in');
      }
      setShowCheckIn(false);
      setCheckInPaymentMethod('');
      setCheckInPaymentReference('');
      // Redirect straight to checkout so the desk can see/settle the bill (room charge already posted).
      setShowCheckout(true);
    } catch (e) {
      toast.error(await apiErrorMessage(e, 'Check-in failed'));
    }
  }

  async function handleCheckOut() {
    try {
      await checkOut.mutateAsync();
      toast.success('Guest checked out');
      router.push(`/${orgSlug}/hotel/rooms`);
    } catch (e) {
      toast.error(await apiErrorMessage(e, 'Check-out failed'));
    }
  }

  if (roomLoading || !room) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  const showEmptyState = !isOccupied && !showCheckIn;

  return (
    <div className="mx-auto w-full max-w-6xl space-y-6 p-4 sm:p-6 lg:px-8">
      <div className="flex items-center gap-3">
        <Link
          href={`/${orgSlug}/hotel/rooms`}
          aria-label="Back to rooms"
          className="p-2 rounded-lg hover:bg-muted transition-colors shrink-0"
        >
          <ArrowLeft className="h-5 w-5" />
        </Link>
        <div className="flex items-center gap-3 min-w-0">
          <div className="size-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
            <BedDouble className="h-5 w-5 text-primary" />
          </div>
          <div className="min-w-0">
            <h1 className="text-xl font-bold text-foreground truncate">Room {room.room_number}</h1>
            <p className="text-sm text-muted-foreground capitalize truncate">{room.room_type.replace('_', ' ')} · Floor {room.floor}</p>
          </div>
        </div>
        <span className={cn(
          'ml-auto shrink-0 text-xs px-3 py-1 rounded-full font-semibold capitalize',
          room.status === 'available' ? 'bg-green-500/10 text-green-700' :
          room.status === 'occupied' ? 'bg-red-500/10 text-red-700' :
          'bg-muted text-muted-foreground'
        )}>
          {room.status}
        </span>
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        {/* Main column — guest info, folio, add-charge, check-in form */}
        <div className="space-y-6 lg:col-span-2">
          {/* Guest info */}
          {isOccupied && guest && (
            <Card>
              <CardContent className="p-5 space-y-3">
                <p className="text-xs font-semibold uppercase text-muted-foreground tracking-wider">Current Guest</p>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 text-sm">
                  {[
                    { label: 'Name', value: [guest.first_name, guest.last_name].filter(Boolean).join(' ') || guest.guest_name },
                    { label: 'Email', value: guest.email || '—' },
                    { label: 'Phone', value: guest.phone },
                    { label: 'Nationality', value: guest.nationality || '—' },
                    { label: guest.id_type ? guest.id_type.replace('_', ' ').replace(/\b\w/g, (c) => c.toUpperCase()) : 'ID', value: guest.id_number },
                    { label: 'Guests', value: `${guest.adults ?? 1} adult(s)${(guest.children ?? 0) > 0 ? `, ${guest.children} child(ren)` : ''}` },
                    { label: 'Check-In', value: new Date(guest.expected_arrival_at || guest.check_in_date).toLocaleString() },
                    { label: 'Check-Out', value: new Date(guest.expected_departure_at || guest.check_out_date).toLocaleString() },
                    { label: 'Nights', value: String(guest.nights) },
                    { label: 'Room Total', value: formatCurrency(guest.total_room_charge, currency), highlight: true },
                  ].map(({ label, value, highlight }) => (
                    <div key={label} className="min-w-0">
                      <p className="text-muted-foreground">{label}</p>
                      <p className={cn('font-semibold truncate', highlight ? 'text-primary' : 'text-foreground')}>{value}</p>
                    </div>
                  ))}
                </div>
                {guest.id_document_url && (
                  <a href={guest.id_document_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-xs text-primary hover:underline">
                    <Receipt className="h-3 w-3" /> View ID document
                  </a>
                )}
              </CardContent>
            </Card>
          )}

          {/* Folio */}
          {isOccupied && folio.length > 0 && (
            <Card>
              <CardContent className="p-5 space-y-3">
                <div className="flex items-center gap-2">
                  <Receipt className="h-4 w-4 text-muted-foreground" />
                  <p className="text-xs font-semibold uppercase text-muted-foreground tracking-wider">Room Folio</p>
                </div>
                <ul className="divide-y divide-border">
                  {folio.map((item) => (
                    <li key={item.id} className="flex items-center justify-between gap-4 py-2.5 text-sm">
                      <div className="min-w-0">
                        <p className="font-medium text-foreground truncate">{item.description}</p>
                        <p className="text-xs text-muted-foreground capitalize">
                          {item.charge_type.replace('_', ' ')}
                          {item.inventory_sku ? ` · ${item.inventory_sku}` : ''}
                        </p>
                      </div>
                      <p className="font-semibold text-foreground shrink-0 tabular-nums">{formatCurrency(item.amount, currency)}</p>
                    </li>
                  ))}
                </ul>
                <div className="flex items-center justify-between pt-2 border-t border-border font-bold text-foreground">
                  <span>Total</span>
                  <span className="text-primary tabular-nums">{formatCurrency(folio.reduce((s, i) => s + i.amount, 0), currency)}</span>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Manual folio charge (minibar / room service / damage); an inventory SKU deducts stock */}
          {isOccupied && (
            <Card>
              <CardContent className="p-4 sm:p-5">
                {!showCharge ? (
                  <button
                    onClick={() => setShowCharge(true)}
                    className="w-full py-2.5 rounded-xl border border-dashed border-border text-sm text-muted-foreground hover:bg-muted hover:border-primary/40 transition-colors"
                  >
                    + Add folio charge (minibar / room service / damage)
                  </button>
                ) : (
                  <div className="space-y-4">
                    <p className="text-xs font-semibold uppercase text-muted-foreground tracking-wider">Add Folio Charge</p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
                      <label className="block sm:col-span-2 lg:col-span-2">
                        <span className="text-xs font-medium text-muted-foreground">Description</span>
                        <input
                          className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
                          placeholder="e.g. Minibar - Coke"
                          value={chargeForm.description}
                          onChange={(e) => setChargeForm((f) => ({ ...f, description: e.target.value }))}
                        />
                      </label>
                      <label className="block">
                        <span className="text-xs font-medium text-muted-foreground">Amount</span>
                        <input
                          type="number" min="0" step="0.01"
                          className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
                          placeholder="0.00"
                          value={chargeForm.amount}
                          onChange={(e) => setChargeForm((f) => ({ ...f, amount: e.target.value }))}
                        />
                      </label>
                      <label className="block">
                        <span className="text-xs font-medium text-muted-foreground">Type</span>
                        <select
                          className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
                          value={chargeForm.charge_type}
                          onChange={(e) => setChargeForm((f) => ({ ...f, charge_type: e.target.value }))}
                        >
                          {CHARGE_TYPES.map((t) => (
                            <option key={t.value} value={t.value}>{t.label}</option>
                          ))}
                        </select>
                      </label>
                      <label className="block sm:col-span-2 lg:col-span-2">
                        <span className="text-xs font-medium text-muted-foreground">Inventory SKU (optional — deducts stock)</span>
                        <input
                          className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-ring"
                          placeholder="SKU"
                          value={chargeForm.inventory_sku}
                          onChange={(e) => setChargeForm((f) => ({ ...f, inventory_sku: e.target.value }))}
                        />
                      </label>
                      {chargeForm.inventory_sku.trim() && (
                        <label className="block">
                          <span className="text-xs font-medium text-muted-foreground">Qty</span>
                          <input
                            type="number" min="1" step="1"
                            className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
                            value={chargeForm.quantity}
                            onChange={(e) => setChargeForm((f) => ({ ...f, quantity: e.target.value }))}
                          />
                        </label>
                      )}
                    </div>
                    <div className="flex gap-3">
                      <button onClick={() => setShowCharge(false)} className="flex-1 py-2.5 rounded-xl border border-border text-sm font-medium hover:bg-muted transition-colors">Cancel</button>
                      <button
                        onClick={submitCharge}
                        disabled={postCharge.isPending}
                        className="flex-1 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm font-semibold hover:bg-primary/90 disabled:opacity-50 transition-colors"
                      >
                        {postCharge.isPending ? 'Adding...' : 'Add Charge'}
                      </button>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          )}

          {/* Check-in form */}
          {showCheckIn && (
            <Card>
              <CardContent className="p-5 sm:p-6 space-y-5">
                <p className="font-semibold text-foreground">Guest Check-In</p>

                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                  <Field label="First Name" value={checkInForm.first_name} onChange={(v) => setField('first_name', v)} placeholder="First name" />
                  <Field label="Last Name" value={checkInForm.last_name} onChange={(v) => setField('last_name', v)} placeholder="Last name" />
                  <Field label="Phone" value={checkInForm.phone} onChange={(v) => setField('phone', v)} placeholder="+254..." />
                  <Field label="Email" type="email" value={checkInForm.email} onChange={(v) => setField('email', v)} placeholder="guest@email.com" />
                  <Field label="Nationality" value={checkInForm.nationality} onChange={(v) => setField('nationality', v)} placeholder="e.g. Kenyan" />
                  <label className="block">
                    <span className="text-sm font-medium text-foreground">ID Type</span>
                    <select
                      value={checkInForm.id_type}
                      onChange={(e) => setField('id_type', e.target.value)}
                      className="mt-1 w-full px-4 py-2.5 rounded-xl border border-input bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                    >
                      <option value="national_id">National ID</option>
                      <option value="passport">Passport</option>
                      <option value="driving_licence">Driving Licence</option>
                      <option value="other">Other</option>
                    </select>
                  </label>
                  <Field label="ID Number *" value={checkInForm.id_number} onChange={(v) => setField('id_number', v)} placeholder="Required — guest ID/passport number" />
                  <Field label="ID Document URL" value={checkInForm.id_document_url} onChange={(v) => setField('id_document_url', v)} placeholder="Uploaded scan link (optional)" />
                  <Field label="Nights (if no dates)" type="number" value={checkInForm.nights} onChange={(v) => setField('nights', v)} placeholder="1" />
                  <Field label="Check-In Date & Time" type="datetime-local" value={checkInForm.expected_arrival_at} onChange={(v) => setField('expected_arrival_at', v)} />
                  <Field label="Check-Out Date & Time" type="datetime-local" value={checkInForm.expected_departure_at} onChange={(v) => setField('expected_departure_at', v)} />
                  <Field label="Adults" type="number" value={checkInForm.adults} onChange={(v) => setField('adults', v)} placeholder="1" />
                  <Field label="Children" type="number" value={checkInForm.children} onChange={(v) => setField('children', v)} placeholder="0" />
                </div>

                {paymentTiming === 'per_day_split' && (
                  <p className="text-xs text-muted-foreground rounded-xl bg-muted/50 px-3 py-2">
                    This property splits the room charge per night — {checkInNights} separate line item{checkInNights !== 1 ? 's' : ''} will be posted to the folio instead of one lump sum.
                  </p>
                )}

                {requiresUpfrontPayment && (
                  <div className="rounded-xl border border-primary/30 bg-primary/5 p-4 space-y-3">
                    <div className="flex items-center justify-between">
                      <p className="text-sm font-semibold text-foreground">Collect Payment (required at check-in)</p>
                      {estimatedCheckInTotal > 0 && (
                        <span className="text-sm font-bold text-primary tabular-nums">~{formatCurrency(estimatedCheckInTotal, currency)}</span>
                      )}
                    </div>
                    <div className="grid grid-cols-3 gap-2">
                      {CHECK_IN_PAYMENT_METHODS.map((m) => {
                        const Icon = m.icon;
                        return (
                          <button
                            key={m.key}
                            type="button"
                            onClick={() => setCheckInPaymentMethod(m.key)}
                            className={cn(
                              'flex flex-col items-center gap-1 py-2.5 rounded-xl border-2 text-xs font-semibold transition-colors',
                              checkInPaymentMethod === m.key ? 'border-primary bg-primary/10 text-primary' : 'border-border text-muted-foreground hover:bg-muted'
                            )}
                          >
                            <Icon className="h-4.5 w-4.5" />
                            {m.label}
                          </button>
                        );
                      })}
                    </div>
                    <label className="block">
                      <span className="text-xs font-medium text-muted-foreground">Reference (optional — M-Pesa code / card approval)</span>
                      <input
                        value={checkInPaymentReference}
                        onChange={(e) => setCheckInPaymentReference(e.target.value.toUpperCase())}
                        placeholder="Code / approval"
                        className="mt-1 w-full px-3 py-2 rounded-lg border border-input bg-background text-sm uppercase focus:outline-none focus:ring-2 focus:ring-ring"
                      />
                    </label>
                  </div>
                )}

                <div className="flex gap-3 pt-1">
                  <button onClick={() => setShowCheckIn(false)} className="flex-1 sm:flex-none sm:px-8 py-2.5 rounded-xl border border-border text-foreground font-medium hover:bg-muted transition-colors">
                    Cancel
                  </button>
                  <button
                    onClick={handleCheckIn}
                    disabled={checkIn.isPending || !checkInForm.first_name.trim() || !checkInForm.id_number.trim() || (requiresUpfrontPayment && !checkInPaymentMethod)}
                    className="flex-1 py-2.5 rounded-xl bg-primary text-primary-foreground font-semibold hover:bg-primary/90 disabled:opacity-50 transition-colors"
                  >
                    {checkIn.isPending ? 'Checking in…' : 'Confirm Check-In'}
                  </button>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Empty state — available room, check-in not yet started */}
          {showEmptyState && (
            <div className="flex flex-col items-center justify-center gap-3 rounded-2xl border border-dashed border-border py-16 text-center text-muted-foreground">
              <div className="size-14 rounded-2xl bg-primary/10 flex items-center justify-center">
                <BedDouble className="h-7 w-7 text-primary" />
              </div>
              <p className="font-medium text-foreground">This room is available</p>
              <p className="text-sm max-w-xs">Check in a guest to open their stay, post room charges, and start the folio.</p>
            </div>
          )}
        </div>

        {/* Sidebar — primary actions, sticky on desktop */}
        <div className="lg:col-span-1">
          <div className="space-y-3 lg:sticky lg:top-6">
            {!isOccupied && !showCheckIn && (
              <button
                onClick={() => setShowCheckIn(true)}
                className="w-full flex items-center justify-center gap-2 py-3 rounded-xl bg-primary text-primary-foreground font-semibold hover:bg-primary/90 transition-colors"
              >
                <LogIn className="h-5 w-5" /> Check In Guest
              </button>
            )}

            {isOccupied && (
              <div className="space-y-3">
                <button
                  onClick={() => setShowCheckout(true)}
                  className="w-full flex items-center justify-center gap-2 py-3 rounded-xl bg-primary text-primary-foreground font-bold hover:bg-primary/90 transition-colors"
                >
                  <Receipt className="h-5 w-5" />
                  Checkout &amp; Settle Bill
                </button>
                <button
                  onClick={() => setShowLate(true)}
                  className="w-full flex items-center justify-center gap-2 py-3 rounded-xl border border-border font-semibold hover:bg-muted transition-colors"
                >
                  <Clock className="h-5 w-5" />
                  Late Checkout
                </button>
                <button
                  onClick={handleCheckOut}
                  disabled={checkOut.isPending}
                  className="w-full flex items-center justify-center gap-2 py-3 rounded-xl border border-destructive/40 text-destructive font-semibold hover:bg-destructive/5 disabled:opacity-50 transition-colors"
                >
                  {checkOut.isPending ? <Loader2 className="h-5 w-5 animate-spin" /> : <LogOut className="h-5 w-5" />}
                  Check Out (no payment)
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      <CheckoutPanel
        roomId={roomId}
        open={showCheckout}
        onClose={() => setShowCheckout(false)}
        onCheckedOut={() => router.push(`/${orgSlug}/hotel/rooms`)}
      />

      {showLate && (
        <div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center bg-black/50 backdrop-blur-sm p-0 sm:p-4" onClick={() => setShowLate(false)}>
          <div className="w-full max-w-sm sm:rounded-2xl rounded-t-2xl bg-card border border-border shadow-2xl" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between px-5 py-4 border-b border-border">
              <h2 className="text-base font-bold text-foreground">Approve Late Checkout</h2>
              <button type="button" aria-label="Close" onClick={() => setShowLate(false)} className="h-8 w-8 rounded-full bg-muted flex items-center justify-center hover:bg-destructive/10 hover:text-destructive transition-colors">
                <X className="h-4 w-4" />
              </button>
            </div>
            <div className="p-5 space-y-4">
              <label className="block">
                <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Surcharge Amount ({currency})</span>
                <input
                  type="number" min={0} step={0.01}
                  value={lateForm.surcharge_amount}
                  onChange={(e) => setLateForm((f) => ({ ...f, surcharge_amount: parseFloat(e.target.value) || 0 }))}
                  className="mt-1.5 w-full px-3 py-2.5 rounded-xl border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring"
                />
              </label>
              <label className="block">
                <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Notes (optional)</span>
                <input
                  value={lateForm.notes}
                  onChange={(e) => setLateForm((f) => ({ ...f, notes: e.target.value }))}
                  placeholder="e.g. 2pm departure agreed"
                  className="mt-1.5 w-full px-3 py-2.5 rounded-xl border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring"
                />
              </label>
              <p className="text-[11px] text-muted-foreground">The surcharge (if any) is posted to the guest&apos;s folio.</p>
              <div className="flex gap-3 pt-1">
                <button type="button" onClick={() => setShowLate(false)} className="flex-1 py-2.5 rounded-xl border border-border text-sm font-medium hover:bg-muted transition-colors">Cancel</button>
                <button
                  onClick={handleLateCheckout}
                  disabled={lateCheckout.isPending}
                  className="flex-1 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm font-semibold hover:bg-primary/90 disabled:opacity-50 transition-colors"
                >
                  {lateCheckout.isPending ? <Loader2 className="h-4 w-4 animate-spin mx-auto" /> : 'Approve'}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function Field({ label, value, onChange, placeholder, type = 'text' }: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
  type?: string;
}) {
  return (
    <label className="block">
      <span className="text-sm font-medium text-foreground">{label}</span>
      <input
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        className="mt-1 w-full px-4 py-2.5 rounded-xl border border-input bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
      />
    </label>
  );
}

export default function RoomDetailPage() {
  return (
    <ModuleGate moduleKey="hotel" fallback={<ModuleUnavailablePage moduleKey="hotel" />}>
      <RoomDetailPageInner />
    </ModuleGate>
  );
}
